Add auto-resize functionality
Calligre/lambda-functions pull request #4
Opened 2016-12-05 07:28 UTC by kyl191

Images now get resized when uploaded to a bucket!

~600ms for the actual resizing with a 768MB container, ~2 sec for the complete activation, download/resize/upload/delete cycle.

Might have to look at the cross posting function, add a bit of delay to make sure the resized file will be available.

2016-12-07 23:30 UTC, TheKevJames requested changes

2016-12-07 23:30 UTC, TheKevJames commented on ResizeImage.py
> +                 os.environ.get('DEST_BUCKET', 'calligre-images'),
Make this a global constant, please.

2016-12-07 23:30 UTC, TheKevJames commented on circle.yml
> +    version: 2.7.11
`2.7.12`?

2016-12-08 01:59 UTC, kyl191 commented on circle.yml
> +    version: 2.7.11
Don't think Lambda is that up to date.

2016-12-08 01:59 UTC, kyl191 commented on ResizeImage.py
> +                 os.environ.get('DEST_BUCKET', 'calligre-images'),
As in declare this when setting the log options?

2016-12-08 07:35 UTC, TheKevJames commented on ResizeImage.py
> +                 os.environ.get('DEST_BUCKET', 'calligre-images'),
Yeah, in global namespace. Just having vars like this all in one place is much easier to find that have to read every line.

2016-12-08 07:36 UTC, TheKevJames commented on circle.yml
> +    version: 2.7.11
6 months is "up to date" but 12 months is not? Kay.

2016-12-08 07:54 UTC, kyl191 commented on circle.yml
> +    version: 2.7.11
Where's 6 months coming from?

In any case, I'm wrong: 
```
return sys.version
"2.7.12 (default, Sep  1 2016, 22:14:00) \n[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]"```

2016-12-08 08:34 UTC, TheKevJames commented on circle.yml
> +    version: 2.7.11
First result for googling "python 2.7.12 release date": https://www.python.org/downloads/release/python-2712/. Sorry, 5.5 months.

2016-12-08 08:35 UTC, TheKevJames approved these changes

2016-12-08 08:35 UTC, merged